COPY (
    SELECT
        OIL_GAS_CODE AS oil_gas_code,
        DISTRICT_NO AS district_no,
        LEASE_NO AS lease_no,
        CYCLE_YEAR AS cycle_year,
        CYCLE_MONTH AS cycle_month,
        OPERATOR_NO AS operator_no,
        FIELD_NO AS field_no,
        TRY_CAST(LEASE_GAS_DISPCD04_VOL AS DOUBLE) AS lease_gas_dispcd04_vol,
        TRY_CAST(LEASE_CSGD_DISPCDE04_VOL AS DOUBLE) AS lease_csgd_dispcde04_vol,
        COALESCE(TRY_CAST(LEASE_GAS_DISPCD01_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_GAS_DISPCD02_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_GAS_DISPCD03_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_GAS_DISPCD04_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_GAS_DISPCD05_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_GAS_DISPCD06_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_GAS_DISPCD07_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_GAS_DISPCD08_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_GAS_DISPCD09_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_GAS_DISPCD99_VOL AS DOUBLE),0) AS lease_gas_total_vol,
        COALESCE(TRY_CAST(LEASE_CSGD_DISPCDE01_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_CSGD_DISPCDE02_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_CSGD_DISPCDE03_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_CSGD_DISPCDE04_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_CSGD_DISPCDE05_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_CSGD_DISPCDE06_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_CSGD_DISPCDE07_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_CSGD_DISPCDE08_VOL AS DOUBLE),0) + COALESCE(TRY_CAST(LEASE_CSGD_DISPCDE99_VOL AS DOUBLE),0) AS lease_csgd_total_vol,
        DISTRICT_NAME AS district_name,
        LEASE_NAME AS lease_name,
        OPERATOR_NAME AS operator_name,
        FIELD_NAME AS field_name
    FROM read_csv('data/pdq/OG_LEASE_CYCLE_DISP_DATA_TABLE.dsv',
        delim='}', header=true, all_varchar=true, ignore_errors=true)
    WHERE COALESCE(TRY_CAST(LEASE_GAS_DISPCD04_VOL AS DOUBLE), 0) > 0
       OR COALESCE(TRY_CAST(LEASE_CSGD_DISPCDE04_VOL AS DOUBLE), 0) > 0
) TO 'data/gas_disposition.parquet' (FORMAT PARQUET);
